services:
  kafka:
    extends:
      file: compose.yaml
      service: kafka

  registry:
    extends:
      file: compose.yaml
      service: registry

  cli:
    extends:
      file: compose.yaml
      service: cli

  effective:
    extends:
      file: compose.yaml
      service: effective

  oracle:
    extends:
      file: compose.yaml
      service: oracle

  keycloak:
    extends:
      file: compose.yaml
      service: keycloak

  admin:
    extends:
      file: compose.yaml
      service: admin
    build:
      context: .
      dockerfile: Dockerfile