services:
  kafka:
    extends:
      file: docker-compose.yml
      service: kafka

  registry:
    extends:
      file: docker-compose.yml
      service: registry

  jaws:
    extends:
      file: docker-compose.yml
      service: jaws

  effective:
    extends:
      file: docker-compose.yml
      service: effective

  oracle:
    extends:
      file: docker-compose.yml
      service: oracle

  keycloak:
    extends:
      file: docker-compose.yml
      service: keycloak

  admin:
    extends:
      file: docker-compose.yml
      service: admin
    build:
      context: .
      dockerfile: Dockerfile