services:
  kafka:
    extends:
      file: deps.yaml
      service: kafka

  registry:
    extends:
      file: deps.yaml
      service: registry

  cli:
    extends:
      file: deps.yaml
      service: cli

  effective:
    extends:
      file: deps.yaml
      service: effective

  oracle:
    extends:
      file: deps.yaml
      service: oracle

  keycloak:
    extends:
      file: deps.yaml
      service: keycloak

  admin:
    hostname: admin
    container_name: admin
    ports:
      - 8443:8443
      - 8080:8080
      - 9990:9990
    depends_on:
      cli:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - SCHEMA_REGISTRY=http://registry:8081
      - KEYCLOAK_REALM=test-realm
      - KEYCLOAK_RESOURCE=jaws
      - KEYCLOAK_SECRET=yHi6W2raPmLvPXoxqMA7VWbLAA2WN0eB
      - KEYCLOAK_FRONTEND_SERVER_URL=http://localhost:8081
      - KEYCLOAK_BACKEND_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_WAR=jaws.war
      - ORACLE_PASS=password
      - ORACLE_SERVER=oracle:1521
      - ORACLE_SERVICE=xepdb1
      - ORACLE_USER=JAWS_OWNER
#    volumes:
#      - ./server.p12:/opt/jboss/wildfly/standalone/configuration/server.p12
