services:
  kafka:
    image: bitnami/kafka:3.5.0
    hostname: kafka
    container_name: kafka
    healthcheck:
      test: kafka-topics.sh --bootstrap-server kafka:9092 --list
      start_period: 30s
      start_interval: 5s
      #      interval: 30s      # waiting for https://github.com/docker/compose/issues/10830
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "9094:9094"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=Cl1akjnHRoG9df2FiSicNg
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LOG_CLEANER_MIN_CLEANABLE_RATIO=0.1
      - KAFKA_CFG_LOG_CLEANER_MAX_COMPACTION_LAG_MS=600000
      - KAFKA_CFG_LOG_CLEANER_MIN_COMPACTION_LAG_MS=300000
      - KAFKA_CFG_LOG_ROLL_MS=300000
      - KAFKA_CFG_LOG_MESSAGE_TIMESTAMP_TYPE=LogAppendTime

  registry:
    image: bitnami/schema-registry:7.4
    hostname: registry
    container_name: registry
    healthcheck:
      test: schema-registry-run-class io.confluent.kafka.schemaregistry.tools.SchemaRegistryPerformance http://localhost:8081 healthcheck 1 1 JSON
      start_period: 30s
      start_interval: 5s
      #      interval: 30s      # waiting for https://github.com/docker/compose/issues/10830
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - 8081:8081
    environment:
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      - SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://kafka:9092

  cli:
    image: jeffersonlab/jaws-libp:5.0.0
    tty: true
    stdin_open: true
    hostname: cli
    container_name: cli
    healthcheck:
      test: test $(list_schemas | wc -l) -gt 20
      start_period: 30s
      start_interval: 5s
      #      interval: 30s      # waiting for https://github.com/docker/compose/issues/10830
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      registry:
        condition: service_healthy
    environment:
      - TZ=America/New_York
      - BOOTSTRAP_SERVERS=kafka:9092
      - SCHEMA_REGISTRY=http://registry:8081
      - LOGLEVEL=INFO

  effective:
    hostname: effective
    container_name: effective
    image: jeffersonlab/jaws-effective-processor:5.0.0
    healthcheck:
      test: test $(ps | grep jaws | wc -l) -gt 1
      start_period: 30s
      start_interval: 5s
      #      interval: 30s      # waiting for https://github.com/docker/compose/issues/10830
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      cli:
        condition: service_healthy
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY: "http://registry:8081"

  oracle:
    image: gvenzl/oracle-xe:21.3.0
    hostname: oracle
    container_name: oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: testing
      TZ: 'America/New_York'
    volumes:
      - ./container/oracle/initdb.d:/container-entrypoint-initdb.d

  keycloak:
    image: jeffersonlab/keycloak:1.1.1
    hostname: keycloak
    container_name: keycloak
    ports:
      - "8082:8080"
      - "9991:9990"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_HOSTNAME: 'localhost'
      KEYCLOAK_FRONTEND_PORT: '8082'
      KEYCLOAK_SERVER_URL: 'http://keycloak:8080'
      KEYCLOAK_HOME: '/opt/keycloak'
      KEYCLOAK_REALM: 'test-realm'
      KEYCLOAK_RESOURCE: 'jaws'
      KEYCLOAK_SECRET: 'yHi6W2raPmLvPXoxqMA7VWbLAA2WN0eB'
      TZ: 'America/New_York'
    volumes:
      - ./container/keycloak/initdb.d:/container-entrypoint-initdb.d
