services:
  kafka:
    extends:
      file: deps.yml
      service: kafka

  registry:
    extends:
      file: deps.yml
      service: registry

  jaws:
    extends:
      file: deps.yml
      service: jaws

  effective:
    extends:
      file: deps.yml
      service: effective

  oracle:
    extends:
      file: docker-compose.yml
      service: oracle

  keycloak:
    extends:
      file: deps.yml
      service: keycloak

  admin:
    hostname: admin
    container_name: admin
    healthcheck:
      test: curl http://localhost:8080 -sf -o /dev/null
      start_period: 30s
      start_interval: 5s
      #      interval: 30s      # waiting for https://github.com/docker/compose/issues/10830
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - 8443:8443
      - 8080:8080
      - 9990:9990
    depends_on:
      jaws:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - SCHEMA_REGISTRY=http://registry:8081
      - KEYCLOAK_REALM=test-realm
      - KEYCLOAK_RESOURCE=jaws
      - KEYCLOAK_SECRET=yHi6W2raPmLvPXoxqMA7VWbLAA2WN0eB
      - KEYCLOAK_FRONTEND_SERVER_URL=http://localhost:8081
      - KEYCLOAK_BACKEND_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_WAR=jaws.war
#    volumes:
#      - ./server.p12:/opt/jboss/wildfly/standalone/configuration/server.p12
