services:
  kafka:
    extends:
      file: deps.yml
      service: kafka

  registry:
    extends:
      file: deps.yml
      service: registry

  jaws:
    extends:
      file: deps.yml
      service: jaws

  effective:
    extends:
      file: deps.yml
      service: effective

  keycloak:
    extends:
      file: deps.yml
      service: keycloak

  admin:
    hostname: admin
    container_name: admin
    ports:
      - 8443:8443
      - 8080:8080
      - 9990:9990
    depends_on:
      - jaws
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - SCHEMA_REGISTRY=http://registry:8081
      - KEYCLOAK_REALM=test-realm
      - KEYCLOAK_RESOURCE=jaws
      - KEYCLOAK_SECRET=yHi6W2raPmLvPXoxqMA7VWbLAA2WN0eB
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_WAR=jaws.war
#    volumes:
#      - ./server.p12:/opt/jboss/wildfly/standalone/configuration/server.p12
