name: CD

on:
  push:
    paths:
      - 'VERSION'

jobs:
  release:
    uses: jeffersonlab/java-workflows/.github/workflows/gh-release.yml@v1
    with:
      files: build/libs/jaws.war
    secrets: inherit

  docker_publish:
    needs:
      - release
    uses: jeffersonlab/container-workflows/.github/workflows/docker-publish.yml@v1
    with:
      semvertag: ${{ needs.release.outputs.semvertag }}
    secrets: inherit